[package]
name = "azure_sso"
version = "0.1.0"
authors = ["Seth Doty <sethmdoty@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
indicatif = "0.11.0"